apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template: 
    metadata:
      name: my-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1    
  replicas: 3
  selector:
    matchLabels:
      type: front-end      
